# Generated by Django 4.0.1 on 2022-01-31 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_snippets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('snippetmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_snippets.snippetmodel')),
                ('head', models.CharField(blank=True, help_text='max 120 characters', max_length=120)),
                ('title', models.CharField(blank=True, help_text='max 120 characters', max_length=120)),
                ('description', models.CharField(blank=True, help_text='max 120 characters', max_length=120)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=('django_snippets.snippetmodel',),
        ),
    ]
