# Generated by Django 4.0.1 on 2022-02-05 00:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('snippetmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_snippets.snippetmodel')),
                ('header', models.CharField(blank=True, help_text='max 80 characters', max_length=80)),
                ('text_1', tinymce.models.HTMLField(blank=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=('django_snippets.snippetmodel',),
        ),
    ]
