# Generated by Django 4.0.1 on 2022-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='head',
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(blank=True, help_text='max 120 characters', max_length=120),
        ),
    ]
