# Generated by Django 4.0.2 on 2022-02-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='description',
            field=models.TextField(blank=True, help_text='max 160 characters', max_length=160),
        ),
        migrations.AddField(
            model_name='pages',
            name='index',
            field=models.BooleanField(default=True, help_text='if false add &lt;meta name=&quot;robots&quot; content=&quot;noindex&quot;&gt;'),
        ),
        migrations.AddField(
            model_name='pages',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, help_text='For URL Page', max_length=100),
        ),
        migrations.AddField(
            model_name='pages',
            name='title',
            field=models.CharField(blank=True, help_text='max 80 characters', max_length=80),
        ),
    ]
