# Generated by Django 4.0.2 on 2022-02-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_pages_head_alter_pages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(blank=True, help_text='max 120 characters', max_length=160),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(blank=True, help_text='max 120 characters', max_length=80),
        ),
    ]
