# Generated by Django 4.0 on 2022-02-08 21:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_description_pages_index_pages_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='max 80 characters', max_length=80)),
                ('description', models.TextField(blank=True, help_text='max 160 characters', max_length=160)),
                ('keywords', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, help_text='For URL Page', max_length=100)),
                ('index', models.BooleanField(default=True, help_text='if false add &lt;meta name=&quot;robots&quot; content=&quot;noindex&quot;&gt;')),
                ('text_1', tinymce.models.HTMLField(blank=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
