# Generated by Django 4.0 on 2022-02-03 11:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_pages_description_alter_pages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='text_1',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(blank=True, help_text='max 160 characters', max_length=160),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(blank=True, help_text='max 80 characters', max_length=80),
        ),
    ]
