# Generated by Django 4.0 on 2022-02-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pagestwo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagestwo',
            options={'verbose_name': 'PageTwo', 'verbose_name_plural': 'PagesTwo'},
        ),
    ]
