# Generated by Django 4.0 on 2022-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pagestwo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='selected_snippet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagestwo',
            name='selected_snippet',
            field=models.IntegerField(default=0),
        ),
    ]
