# Generated by Django 4.0 on 2022-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_pages_selected_snippet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagestwo',
            name='slug',
        ),
        migrations.AddField(
            model_name='pages',
            name='auto_compile_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagestwo',
            name='auto_compile_title',
            field=models.BooleanField(default=True),
        ),
    ]
