# Generated by Django 4.0.1 on 2022-02-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetmodel',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
